using LiveSplit.Subnautica;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LiveSplit.SubnauticaTracker.Catalogs
{
    internal static class ProgressNameCatalog
    {
        private static readonly IDictionary<string, TechType> TechTypesByNormalizedName =
            Enum.GetValues(typeof(TechType))
                .Cast<TechType>()
                .GroupBy(value => NormalizeIdentifier(value.ToString()), StringComparer.OrdinalIgnoreCase)
                .ToDictionary(group => group.Key, group => group.First(), StringComparer.OrdinalIgnoreCase);

        private static readonly IDictionary<int, string> BlueprintNames =
            new Dictionary<int, string>
            {
                { 3, "Fiber mesh" },
                { 15, "Glass" },
                { 16, "Titanium" },
                { 17, "Silicone rubber" },
                { 27, "Bleach" },
                { 30, "Titanium ingot" },
                { 32, "Copper wire" },
                { 33, "Wiring kit" },
                { 34, "Advanced wiring kit" },
                { 41, "Plasteel ingot" },
                { 42, "Enameled glass" },
                { 43, "Power cell" },
                { 44, "Computer chip" },
                { 53, "Hydrochloric acid" },
                { 56, "Polyaniline" },
                { 57, "Synthetic fibers" },
                { 59, "Aerogel" },
                { 61, "Benzene" },
                { 62, "Lubricant" },
                { 64, "Reactor rod" },
                { 502, "Fins" },
                { 503, "Standard O₂ Tank" },
                { 504, "Battery" },
                { 505, "Survival knife" },
                { 507, "Flashlight" },
                { 508, "Beacon" },
                { 509, "Habitat Builder" },
                { 512, "Compass" },
                { 513, "Air bladder" },
                { 515, "Pipe" },
                { 517, "Pathfinder tool" },
                { 518, "Rebreather" },
                { 519, "Radiation suit" },
                { 522, "Reinforced dive suit" },
                { 523, "Handheld Scanner" },
                { 524, "Fire extinguisher" },
                { 525, "Scanner room HUD chip" },
                { 526, "Floating air pump" },
                { 527, "Creature decoy" },
                { 528, "High Capacity O₂ Tank" },
                { 750, "Repair Tool" },
                { 751, "Seaglide" },
                { 752, "Mobile vehicle bay" },
                { 754, "Flare" },
                { 755, "Stasis Rifle" },
                { 757, "Propulsion Cannon" },
                { 758, "Grav trap" },
                { 759, "Waterproof Locker" },
                { 761, "Laser Cutter" },
                { 762, "Light Stick" },
                { 801, "Thermoblade" },
                { 803, "Lightweight High Capacity Tank" },
                { 804, "Ultra High Capacity Tank" },
                { 805, "Ultra glide fins" },
                { 806, "Swim charge fins" },
                { 807, "Repulsion Cannon" },
                { 808, "Water filtration suit" },
                { 1025, "Cyclops Hull Blueprint" },
                { 1026, "Cyclops Bridge Blueprint" },
                { 1027, "Cyclops Engine Blueprint" },
                { 1500, "Modification station" },
                { 1502, "Fabricator" },
                { 1503, "Aquarium" },
                { 1504, "Locker" },
                { 1505, "Spotlight" },
                { 1516, "Cyclops engine efficiency module" },
                { 1517, "Solar Panel" },
                { 1518, "Sign" },
                { 1519, "Power transmitter" },
                { 1522, "Thermal Plant" },
                { 1524, "Wall locker" },
                { 1525, "Bench" },
                { 1526, "Picture Frame" },
                { 1527, "Basic plant pot" },
                { 1528, "Interior Growbed" },
                { 1529, "Plant shelf" },
                { 1530, "Exterior Growbed" },
                { 1532, "Floodlight" },
                { 1533, "Radio" },
                { 1534, "Composite plant pot" },
                { 1535, "Chic plant pot" },
                { 1536, "Medical Kit Fabricator" },
                { 1537, "Cyclops depth module MK1" },
                { 1538, "Cyclops depth module MK2" },
                { 1539, "Single wall shelf" },
                { 1540, "Wall shelves" },
                { 1541, "Basic Double bed" },
                { 1542, "Quilted double bed" },
                { 1543, "Single bed" },
                { 1544, "Battery charger" },
                { 1545, "Power cell charger" },
                { 1547, "Hatching enzymes" },
                { 1551, "Cyclops shield generator" },
                { 1552, "Cyclops sonar upgrade" },
                { 1553, "Cyclops docking bay repair module" },
                { 1554, "Cyclops Decoy Tube Upgrade" },
                { 1555, "Cyclops fire suppression system" },
                { 1557, "Cyclops thermal reactor module" },
                { 1558, "Cyclops depth module MK3" },
                { 1802, "Desk" },
                { 1803, "Swivel chair" },
                { 1805, "Office chair" },
                { 1806, "Command chair" },
                { 1812, "Coffee vending machine" },
                { 1813, "Bar table" },
                { 1819, "Trash can" },
                { 1820, "Nuclear waste disposal" },
                { 1821, "Vending machine" },
                { 1822, "Counter" },
                { 2000, "Seamoth" },
                { 2001, "Prawn suit" },
                { 2003, "Cyclops" },
                { 2101, "Engine efficiency module" },
                { 2102, "Seamoth solar charger" },
                { 2103, "Storage module" },
                { 2104, "Seamoth perimeter defense system" },
                { 2105, "Hull reinforcement" },
                { 2109, "Seamoth torpedo system" },
                { 2110, "Seamoth sonar" },
                { 2111, "Vortex torpedo" },
                { 2112, "Seamoth depth module MK1" },
                { 2113, "Seamoth depth module MK2" },
                { 2114, "Seamoth depth module MK3" },
                { 2115, "Prawn suit jump jet upgrade" },
                { 2116, "Prawn suit drill arm" },
                { 2117, "Prawn suit thermal reactor" },
                { 2119, "Gas torpedo" },
                { 2120, "Prawn suit propulsion cannon" },
                { 2121, "Prawn suit grappling arm" },
                { 2122, "Prawn suit torpedo arm" },
                { 2128, "Prawn suit depth module MK1" },
                { 2129, "Prawn suit depth module MK2" },
                { 2250, "Scanner room range upgrade" },
                { 2251, "Scanner room speed upgrade" },
                { 4201, "Blue Tablet" },
                { 4202, "Orange Tablet" },
                { 4204, "Purple Tablet" },
                { 4209, "Ion power cell" },
                { 4210, "Ion battery" },
                { 4500, "Filtered water" },
                { 4501, "Disinfected water" },
                { 4502, "Cooked peeper" },
                { 4503, "Cooked holefish" },
                { 4504, "Cooked garryfish" },
                { 4505, "Cooked reginald" },
                { 4506, "Cooked bladderfish" },
                { 4507, "Cooked hoverfish" },
                { 4508, "Cooked spadefish" },
                { 4509, "Cooked boomerang" },
                { 4510, "Cooked eyeye" },
                { 4511, "Cooked oculus" },
                { 4512, "Cooked hoopfish" },
                { 4514, "First aid kit" },
                { 4517, "Cooked spinefish" },
                { 4518, "Cooked Red eyeye" },
                { 4519, "Cooked magmarang" },
                { 4600, "Cured peeper" },
                { 4601, "Cured holefish" },
                { 4602, "Cured garryfish" },
                { 4603, "Cured reginald" },
                { 4604, "Cured bladderfish" },
                { 4605, "Cured hoverfish" },
                { 4606, "Cured spadefish" },
                { 4607, "Cured boomerang" },
                { 4608, "Cured eyeye" },
                { 4609, "Cured oculus" },
                { 4610, "Cured hoopfish" },
                { 4611, "Cured spinefish" },
                { 4612, "Cured red eyeye" },
                { 4613, "Cured magmarang" },
                { 5500, "Multipurpose room" },
                { 5501, "Hatch" },
                { 5504, "Ladder" },
                { 5505, "Window" },
                { 5509, "Foundation" },
                { 5510, "I compartment" },
                { 5511, "L compartment" },
                { 5512, "T compartment" },
                { 5513, "X compartment" },
                { 5514, "Reinforcement" },
                { 5515, "Bulkhead" },
                { 5516, "I Glass compartment" },
                { 5517, "L Glass compartment" },
                { 5518, "Observatory" },
                { 5519, "Vertical connector" },
                { 5520, "Moonpool" },
                { 5522, "Vehicle upgrade console" },
                { 5523, "Planters & Pots" },
                { 5524, "Water filtration machine" },
                { 5525, "Alien containment" },
                { 5526, "Scanner room" },
                { 5527, "Camera drone" },
                { 5528, "Bioreactor" },
                { 5529, "Nuclear reactor" },
                { 5530, "Base-attached air pump" },
                { 5900, "Neptune Launch Platform" },
                { 5901, "Neptune Gantry" },
                { 5902, "Neptune Boosters" },
                { 5903, "Neptune Fuel Reserve" },
                { 5904, "Neptune Cockpit" },
                { 6009, "An unusual doll" },
                { 5534, "Large room" },
                { 5539, "Large room partition door" },
                { 5540, "Multipurpose room glass dome" },
                { 5541, "Large room partition" },
                { 5542, "Large room glass dome" },
            };

        private static readonly IDictionary<string, string> DatabankNames =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "CuteFish", "Cuddlefish" },
                { "AcidMushroom", "Acid Mushroom" },
                { "BrainCoral", "Brain Coral" },
                { "Gasopod", "Gasopod" },
                { "Airsack", "Bladderfish" },
                { "Biter", "Biter" },
                { "Stalker", "Stalker" },
                { "SandShark", "Sand Shark" },
                { "LimestoneOutcrops", "Limestone Outcrops" },
                { "RabbitRay", "Rabbit Ray" },
                { "Boomerang", "Boomerang" },
                { "Garryfish", "Garryfish" },
                { "Peeper", "Peeper" },
                { "Shuttlebug", "Shuttlebug" },
                { "Bleeder", "Bleeder" },
                { "Readme", "Start Here" },
                { "SurvivalChecklist", "Survival Checklist" },
                { "AuroraOverview", "Aurora Ship Status" },
                { "AEPSuit", "All-Environment Protection Suit" },
                { "StalkerTooth", "Stalker Teeth" },
                { "Floater", "Floater" },
                { "Holefish", "Holefish" },
                { "CaveCrawler", "Cave Crawler" },
                { "Lifepod", "2-Berth Emergency Lifepod" },
                { "TableCoral", "Table Coral" },
                { "Creepvine", "Creepvine" },
                { "CreepvineSeeds", "Creepvine Seeds" },
                { "HangingStinger", "Drooping Stinger" },
                { "Hoopfish", "Hoopfish" },
                { "Crash", "Crashfish" },
                { "CrashLair", "Sulfur Plant" },
                { "Eyeye", "Eyeye" },
                { "Hoverfish", "Hoverfish" },
                { "Reginald", "Reginald" },
                { "Spadefish", "Spadefish" },
                { "Reefback", "Reefback Leviathan" },
                { "TigerPlant", "Tiger Plant" },
                { "TreeLeech", "Tree Leech" },
                { "TreeMushroom", "Tree Mushrooms" },
                { "Jellyray", "Jellyray" },
                { "Mesmer", "Mesmer" },
                { "ModificationStation", "Modification Station" },
                { "Seamoth", "Seamoth" },
                { "Moonpool", "Moonpool" },
                { "StasisRifle", "Stasis Rifle" },
                { "PropulsionCannon", "Propulsion Cannon" },
                { "MetalSalvage", "Scattered Wreckage" },
                { "Builder", "Habitat Builder" },
                { "SandstoneOutcrops", "Sandstone Outcrops" },
                { "ShaleOutcrops", "Shale Outcrops" },
                { "Techlight", "Floodlight" },
                { "LEDLight", "Light Stick" },
                { "BasePlanter", "Planters & Pots" },
                { "FarmingTray", "Exterior Growbed" },
                { "PlanterBox", "Interior Growbed" },
                { "WaterFilter", "Water Filtration System" },
                { "HangingFruitTree", "Lantern Tree" },
                { "BulboTree", "Bulbo Tree" },
                { "WhiteMushroom", "Deep Shroom" },
                { "PinkMushroom", "Pink Cap" },
                { "PurpleRattle", "Speckled Rattler" },
                { "PurpleVasePlant", "Ming Plant" },
                { "OrangeMushroom", "Jaffa Cup" },
                { "VegetablePlant", "Chinese Potato Plant" },
                { "MelonPlant", "Marblemelon Plant" },
                { "KooshBush", "Bulb Bush" },
                { "BluePalm", "Blue Palm" },
                { "SmallFan", "Pygmy Fan" },
                { "PurpleFan", "Veined Nettle" },
                { "WrithingWeed", "Writhing Weed" },
                { "JellyPlant", "Gel Sack" },
                { "GabeSFeather", "Gabe's Feather" },
                { "SeaCrown", "Sea Crown" },
                { "MembrainTree", "Membrain Tree" },
                { "PinkFlower", "Voxel Shrub" },
                { "FernPalm", "Fern Palm" },
                { "OrangePetalsPlant", "Grub Basket" },
                { "EyesPlant", "Eye Stalk" },
                { "RedGreenTentacle", "Ghost Weed" },
                { "PurpleStalk", "Violet Beau" },
                { "RedBasketPlant", "Rouge Cradle" },
                { "RedBush", "Redwort" },
                { "RedConePlant", "Regress Shell" },
                { "ShellGrass", "Spiked Horn Grass" },
                { "SpottedLeavesPlant", "Spotted Dockleaf" },
                { "RedRollPlant", "Furled Papyrus" },
                { "PurpleBranches", "Cave Bush" },
                { "SnakeMushroom", "Jellyshroom" },
                { "BloodVine", "Bloodvine" },
                { "Spotlight", "Spotlight" },
                { "IslandsPDABase1Desk", "Degasi Voice Log #2 - Storm!" },
                { "IslandsPDABase1bDesk", "Degasi Voice Log #1 - Habitation Location" },
                { "IslandsPDABase1Interior", "Paul Torgal's Log #1 - Marooned" },
                { "IslandsPDABase1a", "Bart Torgal's Log #3 - Return From the Deep" },
                { "IslandsPDAExterior", "Degasi Voice Log #3 - Aftermath" },
                { "JellyPDABrokenCorridor", "Degasi Voice Log #5 - Pecking Order" },
                { "JellyPDARoom1Desk", "Bart Torgal's Log #1 - This World" },
                { "JellyPDARoom1Locker", "Paul Torgal's Log #2 - Dilemma" },
                { "JellyPDAObservatory", "Bart Torgal's Log #2 - Stalker Teeth" },
                { "JellyPDARoom2Desk", "Degasi Voice Log #6 - Deeper?!" },
                { "JellyPDARoom2Locker", "Degasi Voice Log #4 - Curious Discovery" },
                { "JellyPDAExterior", "Marguerit Maida's Log - Speaking Freely" },
                { "MapRoom", "Scanner Room" },
                { "Lifepod1", "Lifepod 2 Chief Technical Officer Yu's Voicelog (T+2min)" },
                { "Lifepod2", "Lifepod 12 Medical Officer Danby's Crew Log" },
                { "Lifepod3", "Lifepod 3 Crew Log" },
                { "Lifepod4", "Lifepod 13 Emissary's Voicelog" },
                { "LifepodRandom", "Lifepod 7 Crew Log" },
                { "LifepodSeaglide", "Lifepod 17 Crew Log" },
                { "LifepodKeenDialog", "Lifepod 19 Second Officer Keen's Voicelog" },
                { "LifepodKeenLog", "Lifepod 19 Second Officer Keen's Crew Log" },
                { "RendezvousFloatingIsland", "Rendezvous Voicelog" },
                { "LifepodCrashZone1", "Lifepod 6 Crew Log #1" },
                { "LifepodCrashZone2", "Lifepod 6 Crew Log #2" },
                { "LifepodDecoy", "Lifepod 4 Crew Log" },
                { "SeaTreader", "Sea Treader Leviathan" },
                { "ReaperLeviathan", "Reaper Leviathan" },
                { "Crabsquid", "Crabsquid" },
                { "Warper", "Warper" },
                { "Aurora_Office_Terminal1", "Alterra Launches the Aurora" },
                { "Aurora_Office_PDA1", "Notes to self" },
                { "Aurora_Cargo_PDA1", "Aurora Engineering Drone - Log" },
                { "Aurora_Locker_PDA1", "Aurora Auxiliary Mission Orders" },
                { "Aurora_Locker_PDA2", "Sweet Offer" },
                { "Aurora_Living_Area_PDA1", "Trans-Gov Profile: Alterra Corp." },
                { "Aurora_Living_Area_PDA2", "Responsible Autonomous Relationships" },
                { "Aurora_Living_Area_PDA2b", "Relationship Contract Legal Recording" },
                { "Aurora_Living_Area_PDA3", "Today's Menu" },
                { "InnerBiomeWreckLore1", "Degasi Crew Manifest: Paul Torgal" },
                { "InnerBiomeWreckLore2", "Degasi Crew Manifest: Bart Torgal" },
                { "InnerBiomeWreckLore3", "Degasi Crew Manifest: Marguerit Maida" },
                { "InnerBiomeWreckLore4", "Alterra Citizen Testimonials" },
                { "InnerBiomeWreckLore5", "Trans-Gov Profile: Mongolian Independent States" },
                { "InnerBiomeWreckLore7", "Aurora Scanner Room Voice Log" },
                { "OuterBiomeWreckLore1", "VR Suite Log" },
                { "OuterBiomeWreckLore2", "Alterra Alms Pamphlet" },
                { "OuterBiomeWreckLore3", "The Charter" },
                { "OuterBiomeWreckLore4", "What Can We Learn From the Hive Mind of Strader VI?" },
                { "OuterBiomeWreckLore5", "Corporate Profile: Torgal Corp." },
                { "OuterBiomeWreckLore6", "Join Alterra's Board of Directors" },
                { "OuterBiomeWreckLore9", "Surveillance Log, Leisure Deck B" },
                { "OuterBiomeWreckLore10", "Profitability Projections" },
                { "Cyclops", "Cyclops" },
                { "Exo", "Prawn Suit (Mk.III)" },
                { "WaterPark", "Alien Containment" },
                { "NuclearReactor", "Nuclear Reactor" },
                { "ThermalPlant", "Thermal Plant" },
                { "Bioreactor", "Bioreactor" },
                { "LaserCutter", "Laser Cutter" },
                { "Welder", "Repair Tool" },
                { "Seaglide", "Seaglide" },
                { "Crabsnake", "Crabsnake" },
                { "Ampeel", "Ampeel" },
                { "Oculus", "Oculus" },
                { "Boneshark", "Boneshark" },
                { "Aurora_DriveRoom_Terminal1", "Aurora Black Box Data" },
                { "Aurora_RingRoom_Terminal3", "Alterra HQ - Last Recorded Transmissions" },
                { "Aurora_RingRoom_Code_PDA", "Lab Access" },
                { "DeepPDA1", "Degasi Voice Log #7 - Malady" },
                { "DeepPDA2", "Degasi Voice Log #8 - Risk Taking" },
                { "DeepPDA3", "Degasi Voice Log #9 - Disaster" },
                { "DeepPDA4", "Paul Torgal's Log #3 - The End" },
                { "Precursor_Gun_DataDownload1", "Alien Data Terminal" },
                { "Precursor_Gun_DataDownload2", "Enforcement Platform Schematic" },
                { "Precursor_Gun_DataDownload3", "Alien Facility Locations" },
                { "Precursor_LostRiverBase_DataDownload1", "Specimen Research Data" },
                { "Precursor_LostRiverBase_DataDownload2", "Kharaa Contagion Profile" },
                { "Precursor_LostRiverBase_DataDownload3", "Damage report" },
                { "Precursor_LostRiverBase_DataDownload4", "Bacterial Infection Report" },
                { "Precursor_LavaCastleBase_ThermalPlant", "Alien Thermal Plant" },
                { "Precursor_LavaCastleBase_ThermalPlant2", "Primary Containment Facility" },
                { "Precursor_LavaCastleBase_ThermalPlant3", "Fossil Data" },
                { "Precursor_LavaCastleBase_DataDownload1", "Ion Power Data" },
                { "Precursor_SparseReefCache_DataDownload1", "Alien Sanctuary Alpha" },
                { "Precursor_Cache_DataDownload2", "Alien Sanctuary Beta" },
                { "Precursor_Cache_DataDownload3", "Alien Biological History" },
                { "Precursor_Cache_DataDownloadLostRiver", "Fauna Reproductive Data" },
                { "LavaLarva", "Lava Larva" },
                { "LavaLizard", "Lava Lizard" },
                { "SeaDragon", "Sea Dragon Leviathan" },
                { "GhostRay", "Ghostray" },
                { "FireRay", "Crimson Ray" },
                { "TreeCoveTree", "Giant Cove Tree" },
                { "Kyanite", "Kyanite" },
                { "IonCrystal", "Ion Cube" },
                { "SpineEel", "River Prowler" },
                { "StillSuit", "Water Filtration Suit" },
                { "RadSuit", "Radiation Suit" },
                { "ReinforcedSuit", "Reinforced Dive Suit" },
                { "PrecursorEnergyCore", "Energy Core" },
                { "PrecursorKey_Purple", "Purple Tablet" },
                { "PrecursorKey_Blue", "Blue Tablet" },
                { "PrecursorKey_Orange", "Orange Tablet" },
                { "PrecursorKeyTerminal", "Forcefield Control Terminal" },
                { "PrecursorTeleporter", "Alien Arch" },
                { "PrecursorDroid", "Alien Robot" },
                { "Precursor_LostRiverBase_WarperScan", "Self-Warping Quarantine Enforcer Unit" },
                { "Precursor_LostRiverBase_GiantFishSkeleton", "Remains of Research Specimen" },
                { "Precursor_LostRiverBase_SeaDragonSkeleton", "Sea Dragon Skeleton" },
                { "Precursor_LostRiverBase_ScanningCableScan", "Research Probes" },
                { "Precursor_LostRiverBase_CaveSkeletonScan", "Ancient Fossilized Skeleton" },
                { "Precursor_Cache_LostRiverBonesScan", "Mixed Leviathan Fossils" },
                { "Precursor_Cache_LostRiverPlantCaseScan", "Alien Flora Research" },
                { "Precursor_Cache_LostRiverLabTable", "Research Equipment" },
                { "LavaEyeye", "Red Eyeye" },
                { "LavaBoomerang", "Magmarang" },
                { "BloodRoot", "Bloodroot" },
                { "Decoy", "Creature Decoy" },
                { "LavaZone_ReaperSkeleton", "Reaper Leviathan Skeleton" },
                { "PrecursorPrisonArtifact1", "Organic Matter Particulator" },
                { "PrecursorPrisonArtifact2", "Holographic Projector" },
                { "PrecursorPrisonArtifact3", "Rudimentary Tablet" },
                { "PrecursorPrisonArtifact4", "Tracking Implant" },
                { "PrecursorPrisonArtifact5", "Alien Carving" },
                { "PrecursorPrisonArtifact6", "Doomsday Device" },
                { "PrecursorPrisonArtifact7", "Alien Rifle" },
                { "PrecursorPrisonArtifact8", "Ancient Earth Blade" },
                { "PrecursorPrisonArtifact10", "Alien Statue" },
                { "PrecursorPrisonArtifact11", "Translation Device" },
                { "PrecursorPrisonArtifact12", "Alien Building Block" },
                { "PrecursorSurfacePipe", "Alien Vent" },
                { "Precursor_Prison_DataDownload1", "Enzyme 42 Project Data" },
                { "Precursor_Prison_DataDownload2", "Sea Emperor Leviathan Research Data" },
                { "Precursor_Prison_DataDownload3", "Ventilation Control" },
                { "PrecursorPipeRoomIncomingPipe", "Peepers Entering the Containment Facility" },
                { "PrecursorPipeRoomOutgoingPipe", "Enzyme Host Peepers Leaving the Containment Facility" },
                { "PrecursorPrisonLabEmperorFetus", "Sea Emperor Fetus" },
                { "PrecursorPrisonLabEmperorEgg", "Sea Emperor Egg Casing" },
                { "PrecursorPrisonAquariumPipe", "Aquarium Pipe Access Point" },
                { "PrecursorPrisonAquariumFinalTeleporter", "Aquarium Arch" },
                { "PrecursorPrisonAquariumIncubator", "Hatching Enzymes" },
                { "PrecursorPrisonAquariumIncubatorEggs", "The Sea Emperor's Eggs" },
                { "SeaEmperorEggHatchingEnzymes", "Hatching Enzymes Old" },
                { "SeaEmperorLifeCycle", "The Sea Emperor's Lifecycle" },
                { "SeaEmperorBaby", "Sea Emperor Juvenile" },
                { "PrecursorPrisonArtifact13", "Nanobots" },
                { "GhostLeviathan", "Ghost Leviathan" },
                { "GhostLeviathanJuvenile", "Ghost Leviathan Juvenile" },
                { "EarthenCoralTubes", "Earthen Coral Tubes" },
                { "CoralShellPlate", "Coral Shell Plate" },
                { "BigCoralTubes", "Giant Coral Tubes" },
                { "FloatingStones", "Anchor Pods" },
                { "BlueAmoeba", "Amoeboid" },
                { "RedTipRockThings", "Pyrocoral" },
                { "BlueTipLostRiverPlant", "Crab Claw Kelp" },
                { "BlueLostRiverLilly", "Brine Lily" },
                { "BlueprintCorruption", "WARNING: Blueprint Database Corrupted" },
                { "LargeFloater", "Ancient Floater" },
                { "SecondarySystems", "4546B Environment Scan" },
                { "Aurora_BreachScan", "Drive Core Shielding Breach" },
                { "Void", "Crater Edge" },
                { "LostRiver_BonesfieldHugeSkeleton", "Gargantuan Fossil" },
                { "Precursor_LostRiverBase_BrokenAnchor", "Damaged Anchor Cable" },
                { "Precursor_LostRiverBase_Rays", "Ray Species on 4546B" },
                { "Precursor_LostRiverBase_Bones", "Rib Cage Samples" },
                { "Precursor_LostRiverBase_ProductionLine", "Production Line" },
                { "Precursor_LostRiverBase_WarperParts", "Warper Parts" },
                { "Precursor_LostRiverBase_LeviathanEggShellScan", "Sea Dragon Egg" },
                { "PrecursorPrisonIonGenerator", "Ion Cube Fabricator" },
                { "Scanner", "Handheld Scanner" },
                { "SolarPanel", "Solar Panel" },
                { "Fabricator", "Fabricator" },
                { "Aquarium", "Aquarium" },
                { "MVB", "Mobile Vehicle Bay" },
                { "BulkheadDoor", "Bulkhead Door" },
                { "Airpumps", "Air Pumps" },
                { "RepulsionCannon", "Repulsion Cannon" },
                { "AluminiumOxide", "Ruby" },
                { "Magnetite", "Magnetite" },
                { "Nickel", "Nickel Ore" },
                { "Uraninite", "Uraninite" },
                { "Sulphur", "Crystalline Sulfur" },
                { "GiantKooshBush", "Giant Bulb Bush" },
                { "Skyray", "Skyray" },
                { "Rocket", "Neptune Escape Rocket" },
                { "PrisonOutposts", "Sonic Deterrent" },
                { "CaptainCode", "High Security Terminal - Captain's Quarters" },
                { "CaptainPDA", "Captain's Log" },
                { "Infection", "Specimen with Symptoms of Infection" },
                { "JellyPDABreadcrumb", "Environment Log" },
                { "HeroPeeper", "Enzyme Host Peeper" },
                { "AquariumPeeper", "Peepers Inside the Containment Facility" },
                { "CuredCreature", "Specimen with Infection Symptoms Inhibited" },
                { "Spinefish", "Spinefish" },
                { "Blighter", "Blighter" },
                { "Rockgrub", "Rockgrub" },
                { "BloodCrawler", "Blood Crawler" },
                { "TimeCapsule", "Time Capsule" },
                { "UnknownEgg", "Alien Eggs" },
                { "RadioRadiationSuitNoSignalAltDatabank", "Lifepod 4 Transmission Origin" },
                { "RadioShallows22NoSignalAltDatabank", "Lifepod 6 Transmission Origin" },
                { "RadioKelp28NoSignalAltDatabank", "Lifepod 7 Transmission Origin" },
            };

        private static readonly IDictionary<int, string> AchievementNames =
            new Dictionary<int, string>
            {
                { 1, "Getting Your Feet Wet" },
                { 2, "Extinction Event Avoided" },
                { 3, "Ancient Technologies" },
                { 4, "Thermal Activity" },
                { 5, "Follow the Lost River" },
                { 6, "Fourteen Thousand Leagues Under the Sea" },
                { 7, "Optimal Health" },
                { 8, "Leave Only Time Capsules" },
                { 9, "Seaside Living with an Ocean View" },
                { 10, "Follow the Degasi" },
                { 11, "Sea Monsters" },
                { 12, "Settling in for the Long Haul" },
                { 13, "Personal Propulsion" },
                { 14, "40-foot Sub For One" },
                { 15, "Ordered the Prawn" },
                { 16, "Go Among the Stars" },
                { 17, "Man's Best Friend" },
            };

        public static string GetBlueprintName(int id)
        {
            string name;
            return BlueprintNames.TryGetValue(id, out name) ? name : "TechType " + id;
        }

        public static string GetDatabankName(string key)
        {
            string name;
            return key != null && DatabankNames.TryGetValue(key, out name) ? name : key ?? string.Empty;
        }

        public static string GetAchievementName(int id)
        {
            string name;
            return AchievementNames.TryGetValue(id, out name) ? name : "Achievement " + id;
        }

        public static string FormatBlueprint(int id)
        {
            return GetBlueprintName(id) + " - " + GetTechTypeName(id) + " - " + id;
        }

        public static string FormatDatabank(string key)
        {
            string displayName = GetDatabankName(key);
            TechType techType;
            if (TryGetTechType(key, out techType) || TryGetTechType(displayName, out techType))
            {
                return displayName + " - " + techType + " - " + (int)techType;
            }

            return displayName + " - " + (key ?? string.Empty);
        }

        private static string GetTechTypeName(int id)
        {
            string name = Enum.GetName(typeof(TechType), id);
            return name ?? "TechType";
        }

        private static bool TryGetTechType(string value, out TechType techType)
        {
            techType = TechType.None;
            if (string.IsNullOrWhiteSpace(value))
                return false;

            return TechTypesByNormalizedName.TryGetValue(NormalizeIdentifier(value), out techType);
        }

        private static string NormalizeIdentifier(string value)
        {
            return new string((value ?? string.Empty)
                .Where(char.IsLetterOrDigit)
                .ToArray());
        }
    }
}
